### ISSUE TITLE
instance buffer 사용시에 Memory Leak

### ISSUE THREAD

**Issue by ChoWonmin** [hyunwoo/vl-examples#1]
안녕하세요.

아래 코드를 사용해서 일반적인 경우의 three.js와 vue에서 gpu 메모리 누수를 해결했습니다.
``` ts
  private beforeMount() {
    this.scene.dispose();
    this.renderer.dispose();
    this.renderer.forceContextLoss();
    window.cancelAnimationFrame(this.requestAnimationID);
    // @ts-ignore release force
    this.renderer.domElement = null;
    // @ts-ignore release force
    this.renderer = null;
  }
```
그런데 instance buffer 사용할 때는 Memory Leak이 그대로 있어서요.
혹시 instance buffer에서는 또 다른 코드를 추가했나여??

감사합니다.

**Comment by ChoWonmin** [comment]
하하

인스턴스 버퍼 렌더링 코드에 beforeDestroy() 적었네요;;;

beforeMount()를 적어야하는데

해결되었네요... 감사합니다
역시 집단지성

**Comment by hyunwoo** [comment]
하하하하
여기도 참고를 한번 해주시고,
https://stackoverflow.com/questions/21851349/freeing-memory-in-three-js


```
// index.ts
this.renderGroups.forEach(g => g.detachToScene());

// renderGroup.ts
this.geometry.dispose();
this.material.dispose();

```

소스를 추가이후 테스트 진행해보자.
